### ISSUE TITLE
Error when merging the pdf

### ISSUE THREAD

**Issue by wuzhuzhu** [ala-garbaa-pro/nextjs-md-docs-to-pdf#1]
\e[1m\e[39mConvert md to pdf:\e[0m \e[1m\e[94myes\e[0m
Error reading file: [Error: ENOENT: no such file or directory, open './work/docs--next-js----.md'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './work/docs--next-js----.md'
}

**Comment by Salahuddeen** [comment]
@wuzhuzhu  
Check this out https://github.com/Salahuddeen/nextjs-md-docs-to-pdf/commit/ec3154e422c3b6ea96dc595f71e43706804d9538 

Run the Command twice and it worked for me using code spaces.
I've updated the code to work with the new MDX files that NextJS uses. 
I was able to get the MD file for Next 14, but the PDF didn't have the images.

**Comment by ala-garbaa-pro** [comment]
Great update! Happy coding!
